const { Basket } = require('./basket')

const BasketClass = new Basket(10)

BasketClass.addBagel('COF')
BasketClass.addBagel('BGLO')
BasketClass.addBagel('BGLO')
BasketClass.addBagel('BGLO')
BasketClass.addBagel('BGLO')
BasketClass.addBagel('BGLO')
BasketClass.addBagel('BGLO')
BasketClass.addBagel('BGLO')
BasketClass.addBagel('BGLP')
BasketClass.addBagel('COF')
BasketClass.purchaseBasket()
